### ISSUE TITLE
Zehnder ComfoCool interface

### ISSUE THREAD

**Issue by gertst** [michaelarnauts/comfoconnect#56] opened 2022-07-13 06:57 UTC
Hi, 

First, let me thank you for this wonderful library!

I have a Zehnder ComfoCool module connected to my Q600 ventilation unit.
Using the ComfoConnect LAN C with the official Zehnder app, I'm able to interact with this module also:
- reading out if cooling is on or not 
- setting a timer program for cooling

Is this something that can be added to the library? How can I help to reverse engineer the required commands?

Thanks!
Gert

**Comment by michaelarnauts** [comment] 2022-12-02 13:47
Closing as duplicate of #27 

See https://github.com/michaelarnauts/comfoconnect/issues/27

Can you verify the PDO's that @decontamin4t0R suggested?

**Closed by michaelarnauts** 2022-12-02 13:47 UTC
